/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author disco dancer
 */
public class NewJFrame3 extends javax.swing.JFrame implements Runnable,ActionListener {

	boolean flag1,flag2,flag3,flag4;boolean flag5=true;boolean flag6=false;boolean flag7=true;
	 int x1= 10,count=0;		
         int x2= 185,x3=100;
         int y1=40;
         int y2=40,y3=350,y4=400;
         int score=0;
 
         static int x4= 10,x5 = 100,x6=100,cout=0;		
         static int y5=40;
         static int y6=40,y7=350,y8=400;
        mainpanel mp;
       int mx,my;
        Img2 p1;
        Graphics g;
    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        
        
        initComponents();
     mp=new mainpanel();
        jPanel1.add(mp);
        repaint();
        p1=new Img2();
        repaint();
        b1.setEnabled(false);
       
    }
     public void start(){
        Thread th= new Thread(this);
        th.start();
        }
 
	public void run()
	{
		while(true)
                    {
                  
              
		if(flag5==true){	
                  x1+=3;x2+=3;
                }
                 if(x2>=1166){
                 flag1=true;
                 flag5=false;
                  }
                 if(flag1==true)
                {
                x2=x2-10;
                x1=x1-10; 
                 }
               
                  if(x1<=200){
                    flag5=true;flag1=false;
                  }
 
                  if(flag3==true){
                
                      y4-=7;
                      y3-=7;
                     
                      if(y3==35 && (x1>=508 &&x1<=858) && (x2>=508 && x2<=858))
                      {
                          score=score+10;
                        JOptionPane.showMessageDialog(null,"YOU SCORED 10"," POOR SHOT", JOptionPane.INFORMATION_MESSAGE);
                       
                       
                          }
                      
                        
                      if(count>2 && y3==35){
                        flag5=flag3=flag1=false;
                        b1.setEnabled(false);
                        b3.setEnabled(false);
                       JOptionPane.showMessageDialog(null,"Sorry GAME OVER, press New GAme to try again"," OOPS!! you loose", JOptionPane.INFORMATION_MESSAGE);
                    b1.setEnabled(true);
                        }
                       
                    if(y3<=-120){
                        y3=350;y4=400;flag3=false;
                    }
                  }
                repaint();
                 
			try
			{
			Thread.sleep (20);
			}
			catch (InterruptedException ex)
			{
			Thread.currentThread().interrupt();
			}
	}
                
	}


	public void paint (Graphics g)
	{
            super.paint(g);
            g.setColor(Color.darkGray);
            g.fillRect(x1, y1,175,10);
          
            
            g.setColor(Color.blue);
            g.fillRect(x1+30, y1,115,10);
           
            g.setColor(Color.green);
            g.fillRect(x1+55, y1,65,10);
           
            g.setColor(Color.yellow);
            g.fillRect(x1+75, y1,20,10);
            
            g.setColor(Color.red);
            g.fillRect(x1+85, y1,5,10);
           
            g.drawLine(683,y3, 683, y4);
        
        }

   @Override
    public void actionPerformed(ActionEvent e) { 
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        b1.setText("f");

        b2.setText("n");

        b3.setText("aa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(b1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(b3)
                .addGap(85, 85, 85)
                .addComponent(b2)
                .addGap(25, 25, 25))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b1))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
