/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class panel extends javax.swing.JPanel {
   static int imagecount=0;
    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
  
//        init();
    }
    @Override
    public void paintComponent(Graphics g)
    {
       Image img=new ImageIcon(getClass().getResource("game1.png")).getImage();     // g.drawString("dsdsdsdsdsd", 30, 30); 
        g.drawImage(img, 0, 0, this);
       Image img1=new ImageIcon(getClass().getResource("dot5.png")).getImage();
       Image img2=new ImageIcon(getClass().getResource("cross.png")).getImage();
        Image img3=new ImageIcon(getClass().getResource("111.png")).getImage();
       // g.drawString("dsdsdsdsdsd", 30, 30); 
        // System.out.println("xvalue"+snakesandladders.xvalue);
         //System.out.println("yvalue"+snakesandladders.yvalue);
      // System.out.println(snakesandladders.y[snakesandladders.yvalue]); 
       //System.out.println(snakesandladders.x[snakesandladders.xvalue]);
       //System.out.println(snakesandladders.y[snakesandladders.yvalue]);
       // g.drawImage(img, WIDTH, WIDTH, this);
       // g.drawImage(img1,snakesandladders.x[snakesandladders.prev+snakesandladders.randomnumber],snakesandladders.y[snakesandladders.prev+snakesandladders.randomnumber], this);
           g.drawImage(img1,snakesandladders.xvalue,snakesandladders.yvalue, this);
           g.drawImage(img2,snakesandladders.xvalue1,snakesandladders.yvalue1, this);
           if(imagecount==1)
           {
               g.drawImage(img3,704,60, this);
           }
           if(imagecount==2)
           {
                g.drawImage(img3,704,100, this);
           }
           if(imagecount==3)
           {
                g.drawImage(img3,720,366, this);
           }
           if(imagecount==4)
           {
             g.drawImage(img3,720,406, this);   
           }
     
           
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

 
 
}
