/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RootPaneContainer;
import javax.swing.border.Border;

/**
 *
 * @author hp 
 */
public class panel1 extends javax.swing.JPanel {
String gd,q1,combo,sq1;
boolean f11=false,f12=false,f13=false,f14=false,f15=false,f16=false,f17=false,f18=false,f19=false,f20=false,f21=false,f22=false,flagger=false;
int i=50;
signuppanel sign;
    /**
     * Creates new form panel1
     */
    public panel1() {
        
        initComponents();
     jButton1.setEnabled(false);
     jButton2.setEnabled(false);
        jTextField3.setEnabled(false);
        setSize(1366,768);
        sign=new signuppanel();
            jPanel1.add(sign);
            repaint();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sq = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        nm = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        cpw = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        ct = new javax.swing.JTextField();
        ans = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        dob = new javax.swing.JTextField();
        pn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 153, 153));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRATION FORM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(51, 0, 51))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1366, 760));
        setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STATE");
        add(jLabel1);
        jLabel1.setBounds(20, 270, 60, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAME");
        add(jLabel2);
        jLabel2.setBounds(20, 40, 50, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADDRESS");
        add(jLabel3);
        jLabel3.setBounds(20, 180, 80, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MOBILE NUMBER");
        add(jLabel4);
        jLabel4.setBounds(20, 310, 120, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GENDER");
        add(jLabel5);
        jLabel5.setBounds(20, 100, 80, 14);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONFIRM PASSWORD");
        add(jLabel6);
        jLabel6.setBounds(20, 500, 150, 14);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("USERNAME");
        add(jLabel7);
        jLabel7.setBounds(20, 400, 80, 14);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SECURITY QUESTION");
        add(jLabel8);
        jLabel8.setBounds(20, 540, 150, 14);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("D.o.B");
        add(jLabel9);
        jLabel9.setBounds(20, 70, 50, 14);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ANSWER");
        add(jLabel10);
        jLabel10.setBounds(20, 600, 90, 14);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PASSWORD");
        add(jLabel11);
        jLabel11.setBounds(20, 440, 90, 14);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CITY");
        add(jLabel13);
        jLabel13.setBounds(20, 220, 50, 14);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PHONE NUMBER");
        add(jLabel14);
        jLabel14.setBounds(320, 170, 110, 14);

        sq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "              ----------------------------", "CHOOSE A QUESTION", "WHO IS YOUR FAVOURITE ACTOR?", "WHO WAS YOUR FIRST CRUSH?", "WHAT IS YOUR FAVOURITE CHOCOLATE?", "WHAT IS YOUR CURRENT PHONE NO?", " ", " " }));
        sq.setToolTipText("choose a question matching your password");
        sq.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sqItemStateChanged(evt);
            }
        });
        sq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqActionPerformed(evt);
            }
        });
        add(sq);
        sq.setBounds(180, 540, 220, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1);
        jRadioButton1.setBounds(170, 90, 70, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2);
        jRadioButton2.setBounds(250, 90, 80, 23);

        nm.setToolTipText("enter your name here");
        nm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nmKeyTyped(evt);
            }
        });
        add(nm);
        nm.setBounds(180, 30, 130, 20);

        un.setToolTipText("choose a username for yourself");
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        un.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unFocusLost(evt);
            }
        });
        un.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                unKeyTyped(evt);
            }
        });
        add(un);
        un.setBounds(180, 400, 130, 20);

        pw.setToolTipText("create a password for your account");
        pw.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                pwCaretUpdate(evt);
            }
        });
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        pw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwFocusGained(evt);
            }
        });
        pw.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                pwCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pwKeyTyped(evt);
            }
        });
        add(pw);
        pw.setBounds(180, 440, 130, 20);

        cpw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpwFocusLost(evt);
            }
        });
        cpw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpwKeyTyped(evt);
            }
        });
        add(cpw);
        cpw.setBounds(180, 500, 130, 20);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel15);
        jLabel15.setBounds(340, 500, 170, 20);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel16);
        jLabel16.setBounds(330, 470, 200, 10);

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel17);
        jLabel17.setBounds(340, 470, 220, 20);

        mn.setToolTipText("enter your cell number");
        mn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mnKeyTyped(evt);
            }
        });
        add(mn);
        mn.setBounds(180, 310, 130, 20);

        st.setToolTipText("enter present state");
        st.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stKeyTyped(evt);
            }
        });
        add(st);
        st.setBounds(180, 270, 130, 20);

        ct.setToolTipText("enter your current city");
        ct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctKeyTyped(evt);
            }
        });
        add(ct);
        ct.setBounds(180, 220, 130, 20);

        ans.setToolTipText("answer the previously chosen question");
        ans.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ans.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ansFocusLost(evt);
            }
        });
        ans.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ansKeyTyped(evt);
            }
        });
        add(ans);
        ans.setBounds(180, 600, 130, 23);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);

        add.setColumns(20);
        add.setRows(5);
        add.setToolTipText("enter ur postal address");
        add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                addKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(add);

        add(jScrollPane1);
        jScrollPane1.setBounds(180, 140, 120, 50);

        dob.setToolTipText("enter date of birth here.\nFormat:- dd/mm/yyyy");
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobKeyTyped(evt);
            }
        });
        add(dob);
        dob.setBounds(180, 60, 130, 20);

        pn.setToolTipText("enter your landline number");
        pn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnKeyTyped(evt);
            }
        });
        add(pn);
        pn.setBounds(430, 170, 130, 20);
        add(jSeparator1);
        jSeparator1.setBounds(0, 360, 760, 10);

        jButton1.setText("CREATE ACCOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(180, 630, 150, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        add(jLabel12);
        jLabel12.setBounds(340, 400, 150, 20);

        jTextField1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.setText("EX:  DD-MM-YYYY");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.setOpaque(false);
        add(jTextField1);
        jTextField1.setBounds(340, 60, 170, 20);

        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        add(jTextField3);
        jTextField3.setBounds(180, 570, 350, 16);

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        add(jLabel18);
        jLabel18.setBounds(370, 430, 140, 20);
        add(jProgressBar1);
        jProgressBar1.setBounds(180, 470, 130, 14);

        jButton2.setText("Sign-in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(360, 630, 180, 30);

        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1);
        jPanel1.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void sqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String nm1=nm.getText();
            String dob1=dob.getText();
            String add1=add.getText();
            String pn1=pn.getText();
            String ct1=ct.getText();
            String st1=st.getText();
            String mn1=mn.getText();
            String un1=un.getText();
            String pw1=pw.getText();
            String cpw1=cpw.getText();
            if(flagger==false)
            {
            sq1=sq.getSelectedItem().toString();
            }
           
            String ans1=ans.getText();
            String gd1=gd;
            dbconnect db=new dbconnect();
            String query="INSERT INTO gamebox.reg_details (`name`, dob, gender, address, phone, city, `state`, mobile, username, password, securityq, answer) VALUES ('"+nm1+"','"+dob1+"', '"+gd1+"', '"+add1+"','"+pn1+"', '"+ct1+"', '"+st1+"', '"+mn1+"', '"+un1+"', '"+pw1+"', '"+sq1+"', '"+ans1+"')";
            String q="INSERT INTO gamebox.login_details (username, password) VALUES ('"+un1+"','"+pw1+"')";
            String q111="INSERT INTO gamebox.credit_info (name,credits) VALUES ('"+un1+"','"+String.valueOf(i) +"')";
            db.getInsert(query);
            db.getInsert(q);
            db.getInsert(q111);
             JOptionPane.showMessageDialog(this,"Please Sign in to browse your account","Sign up SUCCESSFUL",JOptionPane.INFORMATION_MESSAGE);
             jButton2.setEnabled(true);
           
         
        } catch (SQLException ex) {
            Logger.getLogger(panel1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         gd=jRadioButton1.getText();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
          gd=jRadioButton2.getText();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void pwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyPressed
         boolean b;
        b=Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if(b==true)
        {
            jLabel18.setText("caps lock is on");
        }
        if(b==false)
        {
            jLabel18.setText("");
        }
        q1=pw.getText();
       if(q1.length()<4){
           jLabel17.setText("password is weak");
       }
       if(q1.length()>=4 && q1.length()<7 ){
           jLabel17.setText("password is strong");
       }
        if(q1.length()>=7 ){
           jLabel17.setText("password is very strong");
       }
       // if(evt.getKeyCode()==KeyEvent.VK_CAPS_LOCK){
         //  jLabel15.setText("caps lock key is on");
           
      // }
       
    }//GEN-LAST:event_pwKeyPressed

    private void cpwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpwFocusLost
if(cpw.getText().equals(pw.getText()))
{
    jLabel15.setText("password matches");
}
else{
        jLabel15.setText("password does not match");
}
    
    }//GEN-LAST:event_cpwFocusLost

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
        
    }//GEN-LAST:event_pwActionPerformed

    private void unFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unFocusLost
        try {
            String u=un.getText();   
            dbconnect d=new dbconnect();
            String q="Select username from login_details";
            ResultSet rs=d.getSelect(q);
            while(rs.next())
            {
                String user=rs.getString("username");
                if(u.equals(user))
                {
                    jLabel12.setText("username already exists, choose other");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(panel1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_unFocusLost

    private void pwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwFocusGained
        boolean b;
        b=Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
        if(b==true)
        {
            jLabel18.setText("caps lock is on");
        }
        if(b==false)
        {
            jLabel18.setText("");
        }
    }//GEN-LAST:event_pwFocusGained

    private void nmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmKeyTyped
        f11=true;
        jButton1.setEnabled(false);
        if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_nmKeyTyped

    private void dobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyTyped
        f12=true;
        jButton1.setEnabled(false);
        if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_dobKeyTyped

    private void addKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addKeyTyped
        f13=true;
        jButton1.setEnabled(false);
        if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_addKeyTyped

    private void pnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnKeyTyped
        f14=true;
        jButton1.setEnabled(false);
        if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_pnKeyTyped

    private void ctKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctKeyTyped
       f15=true;
       jButton1.setEnabled(false);
       if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_ctKeyTyped

    private void stKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stKeyTyped
        f16=true;
        jButton1.setEnabled(false);
        if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_stKeyTyped

    private void mnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mnKeyTyped
        f17=true;
        jButton1.setEnabled(false);
        if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_mnKeyTyped

    private void unKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unKeyTyped
       f18=true;
       jButton1.setEnabled(false);
       if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_unKeyTyped

    private void pwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwKeyTyped
       f19=true;
       jButton1.setEnabled(false);
       if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_pwKeyTyped

    private void cpwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpwKeyTyped
      f20=true;
      jButton1.setEnabled(false);
      if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_cpwKeyTyped

    private void sqItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sqItemStateChanged
       f21=true;
       jButton1.setEnabled(false);
       if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
       jTextField3.setEnabled(false);
       if(sq.getSelectedItem().equals(" ----------------------------"))
       {
           jTextField3.setEnabled(true);
           jTextField3.setText("invalid choice,choose appropriate question");
       }
       else if(sq.getSelectedItem().equals("CHOOSE A QUESTION"))
       {
           jTextField3.setEnabled(true);
           jTextField3.setText("enter your question here");
           flagger=true;
       }
    }//GEN-LAST:event_sqItemStateChanged

    private void ansKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ansKeyTyped
       f22=true;
       jButton1.setEnabled(false);
       if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_ansKeyTyped

    private void ansFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ansFocusLost
       if(f11=true&&f12==true&&f13==true&&f14==true&&f15==true&&f16==true&&f17==true&&f18==true&&f19==true&&f20==true&&f21==true&&f22==true)
       {
           jButton1.setEnabled(true);
       }
    }//GEN-LAST:event_ansFocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
       if(flagger==true)
       {
           sq1=jTextField3.getText();
       }
    }//GEN-LAST:event_jTextField3FocusLost

    private void unFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unFocusGained
        jLabel12.setText("");
    }//GEN-LAST:event_unFocusGained

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void pwCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pwCaretPositionChanged
      
       
        
    }//GEN-LAST:event_pwCaretPositionChanged

    private void pwCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_pwCaretUpdate
         int x=pw.getText().length();
         jProgressBar1.setValue(x*10);
    }//GEN-LAST:event_pwCaretUpdate

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       mainpage mpage=new mainpage();
       mpage.setSize(1366, 768);
       mpage.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add;
    private javax.swing.JTextField ans;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField cpw;
    private javax.swing.JTextField ct;
    private javax.swing.JTextField dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField mn;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField pn;
    private javax.swing.JPasswordField pw;
    private javax.swing.JComboBox sq;
    private javax.swing.JTextField st;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
