/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class sal_cpu_panel extends javax.swing.JPanel {
static int imagecounter=0;
    /**
     * Creates new form sal_cpu_panel
     */
    public sal_cpu_panel() {
        initComponents();
    }
    @Override
 public void paintComponent(Graphics g)
    {
       Image imag=new ImageIcon(getClass().getResource("game1.png")).getImage();     // g.drawString("dsdsdsdsdsd", 30, 30); 
        g.drawImage(imag, 0, 0, this);
         Image img11=new ImageIcon(getClass().getResource("dot5.png")).getImage();
       Image img12=new ImageIcon(getClass().getResource("cross.png")).getImage();
        Image img13=new ImageIcon(getClass().getResource("111.png")).getImage();
          g.drawImage(img11,SAL_AI.xivalue,SAL_AI.yivalue, this);
           g.drawImage(img12,SAL_AI.xivalue1,SAL_AI.yivalue1, this);
           if(imagecounter==1)
           {
               g.drawImage(img13,696,149, this);
           }
           if(imagecounter==2)
           {
                g.drawImage(img13,696,194, this);
           }
           if(imagecounter==3)
           {
                g.drawImage(img13,696,293, this);
           }
           if(imagecounter==4)
           {
             g.drawImage(img13,696,336, this);   
           }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
