/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import sun.java2d.pipe.DrawImage;



/**
 *
 * @author hp
 */
public class snakesandladders extends javax.swing.JFrame {
static int x[],y[];
static int randomnumber=0,randomnumber1=0;
boolean firstsix=false,firstsix1=false;boolean flagger=false;
static int prev=0,xvalue=704,yvalue=60,prev1=0, xvalue1=704,yvalue1=100;

Graphics g;
   panel p;
    /**
     * Creates new form snakesandladders
     */
    public snakesandladders() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        x=new int[110];                   //57 blocks, 58:p1 wins, 59:p2 wins, 60:p1 starts, 61:p2 starts
        y=new int[110];
        init();
        setSize(1366,768);
        p=new panel();
        jPanel1.add(p);
      
        
       
        
        
     
    }
    public void init()
    {
       x[1]=26;  x[2]=96;  x[3]=165;  x[4]=232; x[5]=300;  x[6]=365; x[7]=435;  x[8]=502; x[9]=572; x[10]=641;
       y[1]=647; y[2]=647; y[3]=647; y[4]=647; y[5]=650; y[6]=647; y[7]=647; y[8]=647; y[9]=647; y[10]=647;
       x[20]=26;  x[19]=96;  x[18]=165;  x[17]=232; x[16]=300;  x[15]=365; x[14]=435;  x[13]=502; x[12]=572; x[11]=641;
       y[20]=573; y[19]=573; y[18]=573; y[17]=573; y[16]=573; y[15]=573; y[14]=573; y[13]=573; y[12]=573; y[11]=573;
       x[21]=26;  x[22]=96;  x[23]=165;  x[24]=232; x[25]=300;  x[26]=365; x[27]=435;  x[28]=502; x[29]=572; x[30]=641;
       y[21]=506; y[22]=506; y[23]=506; y[24]=506; y[25]=506; y[26]=506; y[27]=506; y[28]=506; y[29]=506; y[30]=506;
       x[40]=26;  x[39]=96;  x[38]=165;  x[37]=232; x[36]=300;  x[35]=365; x[34]=435;  x[33]=502; x[32]=572; x[31]=641;
       y[40]=441; y[39]=441; y[38]=441; y[37]=441; y[36]=441; y[35]=441; y[34]=441; y[33]=441; y[32]=441; y[31]=441;
       x[41]=26;  x[42]=96;  x[43]=165;  x[44]=232; x[45]=300;  x[46]=365; x[47]=435;  x[48]=502; x[49]=572; x[50]=641;
       y[41]=370; y[42]=370; y[43]=370; y[44]=370; y[45]=370; y[46]=370; y[47]=370; y[48]=370; y[49]=370; y[50]=370;
       x[60]=26;  x[59]=96;  x[58]=165;  x[57]=232; x[56]=300;  x[55]=365; x[54]=435;  x[53]=502; x[52]=572; x[51]=641;
       y[60]=301; y[59]=301; y[58]=301; y[57]=301; y[56]=301; y[55]=301; y[54]=301; y[53]=301; y[52]=301; y[51]=301;
       x[61]=26;  x[62]=96;  x[63]=165;  x[64]=232; x[65]=300;  x[66]=365; x[67]=435;  x[68]=502; x[69]=572; x[70]=641;
       y[61]=232; y[62]=232; y[63]=232; y[64]=232; y[65]=232; y[66]=232; y[67]=232; y[68]=232; y[69]=232; y[70]=232;
       x[80]=26;  x[79]=96;  x[78]=165;  x[77]=232; x[76]=300;  x[75]=365; x[74]=435;  x[73]=502; x[72]=572; x[71]=641;
       y[80]=163; y[79]=163; y[78]=163; y[77]=163; y[76]=163; y[75]=163; y[74]=163; y[73]=163; y[72]=163; y[71]=163;
        x[81]=26;  x[82]=96;  x[83]=165;  x[84]=232; x[85]=300;  x[86]=365; x[87]=435;  x[88]=502; x[89]=572; x[90]=641;
       y[81]=94; y[82]=94; y[83]=94; y[84]=94; y[85]=94; y[86]=94; y[87]=94; y[88]=94; y[89]=94; y[90]=94;
       x[100]=26;  x[99]=96;  x[98]=165;  x[97]=232; x[96]=300;  x[95]=365; x[94]=435;  x[93]=502; x[92]=572; x[91]=641;
       y[100]=30; y[99]=30; y[98]=30; y[97]=30; y[96]=30; y[95]=30; y[94]=30; y[93]=30; y[92]=30; y[91]=30;
    }
   
 

         
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(800, 0, 110, 30);

        jButton1.setText("P1 Dice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton1FocusLost(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 70, 130, 23);

        jButton2.setText("Rules");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(830, 290, 90, 23);

        jButton3.setText("P2 Dice");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton3FocusLost(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(790, 110, 130, 23);

        jLabel2.setText("p1 status");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(850, 160, 170, 30);

        jLabel3.setText("p2 status");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(850, 200, 180, 30);

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 750);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(750, 330, 330, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(750, 480, 290, 20);

        jLabel1.setText("Start position area");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(810, 340, 170, 14);

        jButton4.setText("newgame");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(830, 260, 90, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(810, 34, 170, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel4.setText("");
        Randominteger ri=new Randominteger();
        randomnumber=ri.generaterandom();
        jTextField1.setText(String.valueOf(randomnumber));
        if(randomnumber==6&&firstsix==true)
        {
            jLabel4.setText("player 1 gets a re-chance");
            flagger=true;
        }
        if(prev==80||prev==94||prev==96||prev==97||prev==99||prev==100)
          {
              if(prev==100)
              {
                  xvalue=x[100];
                  yvalue=y[100];
                  prev=100;
                  p.repaint();
              }
              if(prev==80)
              {
                  xvalue=x[100];
                  yvalue=y[100];
                  prev=100;
                  p.repaint();
                  
                  JOptionPane.showMessageDialog(rootPane,"player 1 wins the game","PLAYER 1 WINNER",JOptionPane.INFORMATION_MESSAGE);
              }
              else if(prev==94) 
              {
                    if(randomnumber==6)
                  {
                      xvalue=x[100];
                      yvalue=y[100];
                     prev=100;
                     p.repaint();
                     
                     JOptionPane.showMessageDialog(rootPane,"player 1 wins the game","PLAYER 1 WINNER",JOptionPane.INFORMATION_MESSAGE);
                  }
                  else if(randomnumber==5)
                  {
                      xvalue=x[99];
                      yvalue=y[99];
                      prev=99;
                      p.repaint();
                  }
                  else if(randomnumber==4)
                  {
                      xvalue=x[79];
                      yvalue=y[79];
                      prev=79;
                      p.repaint();
                  }
                  else if(randomnumber==3)
                  {
                      xvalue=x[97];
                      yvalue=y[97];
                      prev=97;
                      p.repaint();
                  }
                  else if(randomnumber==2)
                  {
                      xvalue=x[96];
                      yvalue=y[96];
                      prev=96;
                      p.repaint();
                  }
                   else if(randomnumber==1)
                  {
                      xvalue=x[75];
                      yvalue=y[75];
                      prev=75;
                      p.repaint();
                  }
                  
                 }
              else if(prev==96)
              {
                  if(randomnumber>4)
                  {
                      xvalue=x[96];
                      yvalue=y[96];
                      prev=96;
                      p.repaint();
                   }
                  else if(randomnumber==4)
                  {
                  xvalue=x[100];
                  yvalue=y[100];
                  prev=100;
                  p.repaint();
                  
                  JOptionPane.showMessageDialog(rootPane,"player 1 wins the game","PLAYER 1 WINNER",JOptionPane.INFORMATION_MESSAGE);
                  }
                   else if(randomnumber==3)
                  {
                      xvalue=x[99];
                      yvalue=y[99];
                      prev=99;
                      p.repaint();
                  }
                  else if(randomnumber==2)
                  {
                      xvalue=x[79];
                      yvalue=y[79];
                      prev=79;
                      p.repaint();
                  }
                   else if(randomnumber==1)
                  {
                      xvalue=x[97];
                      yvalue=y[97];
                      prev=97;
                      p.repaint();
                  }
              }
              else if(prev==97)
              {
                  
                  if(randomnumber>3)
              {      
                      xvalue=x[97];
                      yvalue=y[97];
                      prev=97;
                      p.repaint();
                   
              }
                  else if(randomnumber==3)
                  {
                      xvalue=x[100];
                  yvalue=y[100];
                  prev=100;
                  p.repaint();
                  
                  JOptionPane.showMessageDialog(rootPane,"player 1 wins the game","PLAYER 1 WINNER",JOptionPane.INFORMATION_MESSAGE);
                  }
                  else if(randomnumber==2)
                  {
                      xvalue=x[99];
                      yvalue=y[99];
                      prev=99;
                      p.repaint();
                  }
                   else if(randomnumber==1)
                  {
                      xvalue=x[79];
                      yvalue=y[79];
                      prev=79;
                      p.repaint();
                  }
                  
              }
              else if(prev==99) 
              {
                  if(randomnumber>1)
                  {
                      xvalue=x[99];
                      yvalue=y[99];
                      prev=99;
                      p.repaint();
                  }
                  if(randomnumber==1)
              {
                   xvalue=x[100];
                  yvalue=y[100];
                  prev=100;
                  p.repaint();
                  
                  JOptionPane.showMessageDialog(rootPane,"player 1 wins the game","PLAYER 1 WINNER",JOptionPane.INFORMATION_MESSAGE);
              }
          }
             
              
          }
        else
        {
        if(firstsix==false)  
       {
           if(randomnumber!=6)
           {
           jLabel2.setText("p1 cannot start");
           p.repaint();
            
       }
         if (randomnumber==6)
        {
            jLabel2.setText("p1 game started");
            firstsix=true;
            xvalue=720;
            yvalue=366;
            panel.imagecount=1;
            p.repaint();
              
            
        }
       }
      else if(firstsix=true)
       {
           jLabel2.setText("");
           panel.imagecount=3;
           xvalue=x[prev+randomnumber];
           yvalue=y[prev+randomnumber];
           prev=prev+randomnumber;
           p.repaint();
          if(prev==1||prev==4||prev==9||prev==21||prev==28||prev==51||prev==71||prev==80||prev==17||prev==54||prev==62||prev==64||prev==87||prev==93||prev==95||prev==98)
          {
              if(prev==1)
              {
                   xvalue=x[38];
                   yvalue=y[38];
                   prev=38;
                   p.repaint();
              } 
              else if(prev==4)
              {
                   xvalue=x[14];
                   yvalue=y[14];
                   prev=14;
                   p.repaint();
              } 
              else if(prev==9)
              {
                   xvalue=x[31];
                   yvalue=y[31];
                   prev=31;
                   p.repaint();
              }
              else if(prev==21)
              {
                   xvalue=x[42];
                   yvalue=y[42];
                   prev=42;
                   p.repaint();
              }
              else if(prev==28)
              {
                   xvalue=x[84];
                   yvalue=y[84];
                   prev=84;
                   p.repaint();
              }
              else if(prev==51)
              {
                   xvalue=x[67];
                   yvalue=y[67];
                   prev=67;
                   p.repaint();
              }
              else if(prev==71)
              {
                   xvalue=x[91];
                   yvalue=y[91];
                   prev=91;
                   p.repaint();
              }
              else if(prev==80)
              {
                  xvalue=x[100];
                  yvalue=y[100];
                  prev=100;
                  p.repaint();
                  
                  JOptionPane.showMessageDialog(rootPane,"player 1 wins the game","PLAYER 1 WINNER",JOptionPane.INFORMATION_MESSAGE);
              }
              
              else if(prev==17)
              {
                   xvalue=x[7];
                   yvalue=y[7];
                   prev=7;
                   p.repaint();
              } 
              else if(prev==54)
              {
                   xvalue=x[34];
                   yvalue=y[34];
                   prev=34;
                   p.repaint();
              } 
              else if(prev==62)
              {
                   xvalue=x[19];
                   yvalue=y[19];
                   prev=19;
                   p.repaint();
              }
              else if(prev==64)
              {
                   xvalue=x[60];
                   yvalue=y[60];
                   prev=60;
                   p.repaint();
              }
              else if(prev==87)
              {
                   xvalue=x[24];
                   yvalue=y[24];
                   prev=24;
                   p.repaint();
              }
              else if(prev==93)
              {
                   xvalue=x[73];
                   yvalue=y[73];
                   prev=73;
                   p.repaint();
              }
              else if(prev==95)
              {
                   xvalue=x[75];
                   yvalue=y[75];
                   prev=75;
                   p.repaint();
              }
              else if(prev==98)
              {
                   xvalue=x[79];
                   yvalue=y[79];
                   prev=79;
                   p.repaint();
              }
              
          }
         
               
       }

        
        } 
       if(flagger==false)
       {
           jButton1.setEnabled(false);
           jButton3.setEnabled(true);
       }
       else
       {
           jButton3.setEnabled(false);
           flagger=false;
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       SALrules rule=new SALrules();
       rule.setSize(550,500);
       rule.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jLabel4.setText("");
        Randominteger rj=new Randominteger();
        randomnumber1=rj.generaterandom();
        jTextField1.setText(String.valueOf(randomnumber1));
        if(randomnumber1==6&&firstsix1==true)
        {
            jLabel4.setText("player 2 gets re-chance");
            flagger=true;
        }
     if(prev1==80||prev1==94||prev1==96||prev1==97||prev1==99||prev1==100)
          {
              if(prev1==100)
              {
                  xvalue1=x[100];
                  yvalue1=y[100];
                  prev1=100;
              }
              if(prev1==80)
              {
                  xvalue1=x[100];
                  yvalue1=y[100];
                  prev1=100;
                  p.repaint();
                  JOptionPane.showMessageDialog(rootPane,"player 2 wins the game","PLAYER 2 WINNER",JOptionPane.INFORMATION_MESSAGE);
              }
              else if(prev1==94) 
              {
                    if(randomnumber1==6)
                  {
                      xvalue1=x[100];
                      yvalue1=y[100];
                     prev1=100;
                     p.repaint();
                     JOptionPane.showMessageDialog(rootPane,"player 2 wins the game","PLAYER 2 WINNER",JOptionPane.INFORMATION_MESSAGE);
                  }
                  else if(randomnumber1==5)
                  {
                      xvalue1=x[99];
                      yvalue1=y[99];
                      prev1=99;
                      p.repaint();
                  }
                  else if(randomnumber1==4)
                  {
                      xvalue1=x[79];
                      yvalue1=y[79];
                      prev1=79;
                      p.repaint();
                  }
                  else if(randomnumber1==3)
                  {
                      xvalue1=x[97];
                      yvalue1=y[97];
                      prev1=97;
                      p.repaint();
                  }
                  else if(randomnumber1==2)
                  {
                      xvalue1=x[96];
                      yvalue1=y[96];
                      prev1=96;
                      p.repaint();
                  }
                   else if(randomnumber1==1)
                  {
                      xvalue1=x[75];
                      yvalue1=y[75];
                      prev1=75;
                      p.repaint();
                  }
                  
                 }
              else if(prev1==96)
              {
                  if(randomnumber1>4)
                  {
                      xvalue1=x[96];
                      yvalue1=y[96];
                      prev1=96;
                      p.repaint();
                   }
                  else if(randomnumber1==4)
                  {
                  xvalue1=x[100];
                  yvalue1=y[100];
                  prev1=100;
                  p.repaint();
                  JOptionPane.showMessageDialog(rootPane,"player 2 wins the game","PLAYER 2 WINNER",JOptionPane.INFORMATION_MESSAGE);
                  }
                   else if(randomnumber1==3)
                  {
                      xvalue1=x[99];
                      yvalue1=y[99];
                      prev1=99;
                      p.repaint();
                  }
                  else if(randomnumber1==2)
                  {
                      xvalue1=x[79];
                      yvalue1=y[79];
                      prev1=79;
                      p.repaint();
                  }
                   else if(randomnumber1==1)
                  {
                      xvalue1=x[97];
                      yvalue1=y[97];
                      prev1=97;
                      p.repaint();
                  }
              }
              else if(prev1==97)
              {
                  
                  if(randomnumber1>3)
              {      
                      xvalue1=x[97];
                      yvalue1=y[97];
                      prev1=97;
                      p.repaint();
                   
              }
                  else if(randomnumber1==3)
                  {
                      xvalue1=x[100];
                  yvalue1=y[100];
                  prev1=100;
                  p.repaint();
                  JOptionPane.showMessageDialog(rootPane,"player 2 wins the game","PLAYER 2 WINNER",JOptionPane.INFORMATION_MESSAGE);
                  }
                  else if(randomnumber1==2)
                  {
                      xvalue1=x[99];
                      yvalue1=y[99];
                      prev1=99;
                      p.repaint();
                  }
                   else if(randomnumber1==1)
                  {
                      xvalue1=x[79];
                      yvalue1=y[79];
                      prev1=79;
                      p.repaint();
                  }
                  
              }
              else if(prev1==99) 
              {
                  if(randomnumber1>1)
                  {
                      xvalue1=x[99];
                      yvalue1=y[99];
                      prev1=99;
                      p.repaint();
                  }
                  if(randomnumber1==1)
              {
                   xvalue1=x[100];
                  yvalue1=y[100];
                  prev1=100;
                  p.repaint();
                  JOptionPane.showMessageDialog(rootPane,"player 2 wins the game","PLAYER 2 WINNER",JOptionPane.INFORMATION_MESSAGE);
              }
          }
          }
        else
        {
        
       if(firstsix1==false)  
       {
           if(randomnumber1!=6)
           {
           jLabel3.setText("p2 cannot start");
           p.repaint();
            
       }
         if (randomnumber1==6)
        {
            jLabel3.setText("p2 game started");
            firstsix1=true;
            xvalue1=720;
            yvalue1=406;
            panel.imagecount=2;
            p.repaint();
              
            
        }
       }
      else if(firstsix1=true)
       {
           jLabel3.setText("");
           panel.imagecount=4;
           xvalue1=x[prev1+randomnumber1];
           yvalue1=y[prev1+randomnumber1];
           prev1=prev1+randomnumber1;
           p.repaint();
          if(prev1==1||prev1==4||prev1==9||prev1==21||prev1==28||prev1==51||prev1==71||prev1==80||prev1==17||prev1==54||prev1==62||prev1==64||prev1==87||prev1==93||prev==95||prev1==98)
          {
              if(prev1==1)
              {
                   xvalue1=x[38];
                   yvalue1=y[38];
                   prev1=38;
                   p.repaint();
              } 
              else if(prev1==4)
              {
                   xvalue1=x[14];
                   yvalue1=y[14];
                   prev1=14;
                   p.repaint();
              } 
              else if(prev1==9)
              {
                   xvalue1=x[31];
                   yvalue1=y[31];
                   prev1=31;
                   p.repaint();
              }
              else if(prev1==21)
              {
                   xvalue1=x[42];
                   yvalue1=y[42];
                   prev1=42;
                   p.repaint();
              }
              else if(prev1==28)
              {
                   xvalue1=x[84];
                   yvalue1=y[84];
                   prev1=84;
                   p.repaint();
              }
              else if(prev1==51)
              {
                   xvalue1=x[67];
                   yvalue1=y[67];
                   prev1=67;
                   p.repaint();
              }
              else if(prev1==71)
              {
                   xvalue1=x[91];
                   yvalue1=y[91];
                   prev1=91;
                   p.repaint();
              }
             else if(prev==80)
              {
                  xvalue1=x[100];
                  yvalue1=y[100];
                  prev1=100;
                  p.repaint();
                  JOptionPane.showMessageDialog(rootPane,"player 1 wins the game","PLAYER 1 WINNER",JOptionPane.INFORMATION_MESSAGE);
              }
             
              else if(prev1==17)
              {
                   xvalue1=x[7];
                   yvalue1=y[7];
                   prev1=7;
                   p.repaint();
              } 
              else if(prev1==54)
              {
                   xvalue1=x[34];
                   yvalue1=y[34];
                   prev1=34;
                   p.repaint();
              } 
              else if(prev1==62)
              {
                   xvalue1=x[19];
                   yvalue1=y[19];
                   prev1=19;
                   p.repaint();
              }
              else if(prev1==64)
              {
                   xvalue1=x[60];
                   yvalue1=y[60];
                   prev1=60;
                   p.repaint();
              }
              else if(prev1==87)
              {
                   xvalue1=x[24];
                   yvalue1=y[24];
                   prev1=24;
                   p.repaint();
              }
              else if(prev1==93)
              {
                   xvalue1=x[73];
                   yvalue1=y[73];
                   prev1=73;
                   p.repaint();
              }
              else if(prev1==95)
              {
                   xvalue1=x[75];
                   yvalue1=y[75];
                   prev1=75;
                   p.repaint();
              }
              else if(prev1==98)
              {
                   xvalue1=x[79];
                   yvalue1=y[79];
                   prev1=79;
                   p.repaint();
              }
              
          }
               
       }
        }
      if(flagger==false)
       {
           jButton3.setEnabled(false);
           jButton1.setEnabled(true);
       }
       else
       {
           jButton1.setEnabled(false);
           flagger=false;
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusLost
     // jLabel2.setText("");
    }//GEN-LAST:event_jButton1FocusLost

    private void jButton3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusLost
       // jLabel3.setText("");
    }//GEN-LAST:event_jButton3FocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     randomnumber=0;randomnumber1=0;
     firstsix=false;firstsix1=false;
       prev=0;xvalue=704;yvalue=60;prev1=0; xvalue1=704;yvalue1=100;
       jTextField1.setText("");
       jLabel2.setText("");
       jLabel3.setText("");
       p.repaint();
       flagger=false;
       jButton1.setEnabled(true);
       jLabel4.setText("player 1 turn");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
   
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(snakesandladders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(snakesandladders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(snakesandladders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(snakesandladders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new snakesandladders().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

 
  
    
    
}

